name: habita_on_discount
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  get_it: ^7.6.8
  hive: ^2.2.3
  intl: ^0.19.0
  supabase: ^2.0.9
  uuid: ^4.3.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
